set-option -g status-position top

set -g base-index 1
setw -g pane-base-index 1

set-option -g update-environment "WAYLAND_DISPLAY DISPLAY"

set -g status-interval 1
set -g status-style fg=#ffffff,bg=#332d38

set -g status-left ''
set -g status-right '#(test -f /tmp/pracomer.log && cat /tmp/pracomer.log) %a %h-%d %H:%M '

set -g pane-border-style fg=#332d38
set -g pane-active-border-style fg=#50447f

setw -g window-status-style fg=#a0c0d0,bg=#332d38
setw -g window-status-current-style fg=#ffffff,bg=#50447f,bold

set -g message-style fg=#ffffff,bg=#50447f
set -g message-command-style fg=#ffffff,bg=#50447f

setw -g xterm-keys on
set -ga terminal-overrides ',xterm*:XT'

set -g set-titles on
set -g set-titles-string "#S"
set -g renumber-windows on

set -s escape-time 0
set -g history-limit 10000
set -g repeat-time 0

set -g mouse off
setw -g alternate-screen on

bind-key q kill-pane
bind-key Q kill-window
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind C-o display-popup -E "tms"
bind-key P run-shell 'tmux capture-pane -S -32768 ; tmux save-buffer ~/.tmux/$(date +%Y%m%d_%H%M%S).log ; tmux delete-buffer ; tmux display-message "$(date +%Y%m%d_%H%M%S).log"'
