#!/bin/zsh

[[ "$-" == *i* ]] || return

config_home="$HOME"

. "$config_home"/.config/shell/early-funcs

for file in "$config_home"/.config/{shell,zsh}/rc/*(N); do
    . "$file"
done

source $HOME/.fzf/shell/completion.zsh
source $HOME/.fzf/shell/key-bindings.zsh

alias vim='nvim'
alias n='nvim'

alias kcc='kubectl config current-context'
alias sleep='systemctl suspend'

PS1='$(_get_ps1)'
