#!/bin/sh
alias normcom="alafont --font 'Comic Code' --size '14.0'"
alias bigcom="alafont --font 'Comic Code' --size '16.0'"

alias normbit="alafont --font 'UW ttyp0' --size '14.0'"
alias bigbit="alafont --font 'UW ttyp0' --size '22.0'"

testfont() {
	if [ $# -ne 2 ]; then
		echo "testfont <font-name> <size>" >&2
		return 1
	fi

	alafont --font "$1" --size "$2"
}
