#!/bin/sh
alias q='sudo '
alias lopri='nice -n 19 ionice -c2 -n7 '
alias scan='sudo nmap -n -PN -sT -sU -p-'
alias cf='clang-format -i -style=file'
alias c='ctags --links=no -R .'
alias f='fzf-vim'

alias amfa='aws-mfa --profile work'

alias ssm-us='gossm start --profile work --region us-east-1'
alias ssm-dr='gossm start --profile work --region us-east-2'
alias ssm-ap='gossm start --profile work --region ap-northeast-1'
alias ssm-au='gossm start --profile work-au --region ap-southeast-2'

alias build-up='hcloud server create --name build --image debian-10 --type cx31 --ssh-key tp'
alias build-down='hcloud server delete build'

alias dpsec='docker run --rm -ti --network host -v $PWD:/rose parrotsec/security'

alias ss='sudo systemctl start'
alias st='sudo systemctl stop'
alias sd='sudo systemctl -n 100 status'

alias us='systemctl --user start'
alias ut='systemctl --user stop'
alias ud='systemctl --user -n 100 status'

alias xc='xclip -selection clipboard'

m() {
    moshrc "$@"
}

g(){
    sudo gdb -q /proc/"${1?}"/exe "$1"
}

transfer() {
    curl --upload-file "${1?}" https://transfer.sh
}


alias gam='xgamma -gamma 3'

alias pw='LC_ALL=C tr -dc a-zA-Z0-9 < /dev/urandom | head -c 20; echo'

alias mpva='mpv --no-video'
