#!/bin/sh

soff() {
	rbenv shell 2.4.10
	hue light 1 off
	doreval

}

son() {
	rbenv shell 2.4.10
	hue light 1 on
	doreval
}

woff() {
	rbenv shell 2.4.10
	hue light 2 off
	doreval
}

won() {
	rbenv shell 2.4.10
	hue light 2 on
	doreval
}

sb() {
	rbenv shell 2.4.10
	hue light 1 brightness "${1?}"%
	doreval
}

wb() {
	rbenv shell 2.4.10
	hue light 2 brightness "${1?}"%
	doreval
}
