#!/bin/sh

alias kto='khal new tomorrow'
alias khn='khal new'

alias khw='khal list now 7d'
alias khi='khal interactive'
alias kat='khal at'

alias khup='vdirsyncer sync'

alias khalw='khal_notifier --lookahead 7d'
alias khalto='khal_notifier --lookahead 24h'
alias khaltom='khal_notifier --lookahead 48h'
