#!/bin/bash

alias rd='magnolia recent-dirs'
alias rf='magnolia recent-files'

fzf_down() {
    fzf --height=40% "$@" --reverse
}

fzf_log_directory_change() {
	target_dir="$1"

	db_path="${HOME}/.magnolia.db"
	abs_path="$(pwd)"

	[ "$abs_path" = "$HOME" ] && return
	sqlite3 "$db_path" "INSERT INTO directory_history (path) VALUES ('$abs_path');"
}

fzf_log_file_open() {
	file_path="$1"
	file_type="$2"
	action="$3"
	db_path="${HOME}/.magnolia.db"

	abs_path=$(realpath "$file_path" 2>/dev/null || echo "$file_path")

	sqlite3 "$db_path" "INSERT INTO file_history (path, file_type, action) VALUES ('$abs_path', '$file_type', '$action');"
}

cd() {
	builtin cd "$@" && fzf_log_directory_change "$1"
}

fg() {
	local ext="${file##*.}"
	target_file=$(magnolia change-to-file "$@")
	if [ -n "$target_file" ]; then
		nvim "$target_file" && fzf_log_file_open "$target_file" "$ext" "text_editor"
	fi
}

dg() {
	target_dir=$(magnolia change-to-dir "$@")
	if [ -n "$target_dir" ]; then
		cd "$target_dir" && fzf_log_directory_change "$target_dir"
	fi
}

d() {
	local target_dir
	target_dir=$(fd --hidden --exclude .git --type directory | fzf_down)

	if [ -n "$target_dir" ]; then
		cd "$target_dir" && fzf_log_directory_change "$target_dir"
	fi
}

f() {
	local file
	file=$(fd --hidden --exclude .git | fzf_down)

	if [ -n "$file" ]; then
		local ext="${file##*.}"

		case "$ext" in
		mp4 | mkv | avi | webm)
			action="media_player"
			mpv "$file" && fzf_log_file_open "$file" "$ext" "$action"
			;;
		flac | aiff | aif | mp3 | wav)
			action="audio_player"
			mpv "$file" && fzf_log_file_open "$file" "$ext" "$action"
			;;
		jpg | jpeg | png | webp)
			action="image_viewer"
			nsxiv "$file" && fzf_log_file_open "$file" "$ext" "$action"
			;;
		pdf | epub | mobi)
			action="document_reader"
			sioyek "$file" && fzf_log_file_open "$file" "$ext" "$action"
			;;
		*)
			action="text_editor"
			"$EDITOR" "$file" && fzf_log_file_open "$file" "$ext" "$action"
			;;
		esac
	fi
}

g() {
    year=$(date '+%Y')
    month=$(date "+%B" | tr '[:upper:]' '[:lower:]')
    dirs=(
        "$HOME/misc"
        "$HOME/misc/notes/releases"
        "$HOME/misc/notes/releases/${year}/dailies"
        "$HOME/misc/notes/releases/${year}/${month}"
        "$HOME/.config/mpd/playlists"
        "$HOME/misc/music"
        "$HOME/misc/music/backlog"
        "$HOME/misc/notes"
        "$HOME/misc/notes/nota"
        "$HOME/misc/notes/substack"
        "$HOME/misc/notes/www"
        "$HOME/misc/books"
        "$HOME/misc/screenshots"
        "$HOME/misc/recordings"
        "$HOME/src/github.com"
        "$HOME/src/codeberg.org"
        "$HOME/src/codeberg.org/mtmn"
        "$HOME/src/codeberg.org/mtmn/fly"
        "$HOME/.local/share/chezmoi"
        "$HOME/.config"
        "$HOME/Downloads"
    )
    
    selected=$(printf "%s\n" "${dirs[@]}" | fzf_down)
    
    if [ -n "$selected" ]; then
        cd "$selected" && fzf_log_directory_change "$selected" || return 1
    fi
}
