#!/bin/sh

alias pps='podman ps'
alias ppsa='podman ps -a'

alias plo='podman logs'
alias plo='podman logs -f'

alias pcup='podman-compose up'
alias pcupd='podman-compose up -d'

alias pcdo='podman-compose down'
alias pcst='podman-compose stop'

alias pbu='podman build'
alias pcbu='podman-compose build'
