#!/bin/sh

alias pst='podman stats'

alias pps='podman ps'
alias ppsa='podman ps -a'

alias plo='podman logs'
alias plof='podman logs -f'

alias pcu='podman-compose up'
alias pcud='podman-compose up -d'

alias pcd='podman-compose down'
alias pcs='podman-compose stop'

alias pbu='podman build'
