[general]
use-envelope-from = true
pgp-provider=gpg

#log-file=
#log-level=info

[ui]
border-char-vertical="│"
border-char-horizontal="─"
styleset-name=mine

[viewer]
pager=moor
alternatives=text/html,text/plain
header-layout=From|To,Cc|Bcc,Date,Subject

[compose]
address-book-cmd=khard email --parsable --remove-first-line %s
editor=nvim

[filters]
text/plain=bat -P --style=plain
text/calendar=calendar
message/delivery-status=colorize
message/rfc822=colorize
text/html=pandoc -f html -t plain

[openers]
x-scheme-handler/http*=printf '%s' {} | wl-copy

[hooks]
mail-received=[ "$AERC_ACCOUNT" = "fastmail" ] && notify-send -a aerc "$AERC_FROM_ADDRESS" "$AERC_SUBJECT" || true
