#!/bin/zsh

TWITCH_CHANNELS_FILE="$HOME/.config/twitch/channels"

tww() {
	local channel="${1?Usage: tww <channel>}"
	mpv "https://twitch.tv/$channel" --no-terminal --no-resume-playback &
	disown
}

twe() {
	"$EDITOR" "$TWITCH_CHANNELS_FILE"
}

_twitch_completion() {
	local -a channels
	if [[ -f "$TWITCH_CHANNELS_FILE" ]]; then
		while IFS= read -r line; do
			channels+=("${line%% *}")
		done <"$TWITCH_CHANNELS_FILE"
		_describe 'twitch channels' channels
	fi
}

compdef _twitch_completion tww
