#!/bin/sh

export EDITOR=nvim
export LC_COLLATE=C
export PAGER=less
export LESS=-R
export VISUAL=nvim
export PYTHONDONTWRITEBYTECODE=1
export PYTHONSTARTUP="$HOME/.pythonrc"
export BROWSER=firefox
export NSS_DEFAULT_DB_TYPE=sql
export BC_ENV_ARGS="$HOME/.config/bcrc"
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
export GRAB_HOME="$HOME/src"
export LEDGER_FILE="$HOME/misc/random/hledger/2025.journal"
export GOPATH="$HOME/src/misc/go"

# shellcheck disable=SC2154
{
    export PATH="$config_home/.zvm/bin:$config_home/.node_modules/bin:$config_home/bin:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/bin/site_perl:config_home/bin:$config_home/.local/bin:$config_home/.cargo/bin:$config_home/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/share/bcc:/usr/share/bcc/tools"
}

umask 0022
