#!/bin/sh

export EDITOR=vim
export LC_COLLATE=C
export PAGER=less
export VISUAL=vim
export PYTHONDONTWRITEBYTECODE=1
export PYTHONSTARTUP="$HOME/.pythonrc"
export BROWSER=firefox
export NSS_DEFAULT_DB_TYPE=sql
export BC_ENV_ARGS="$HOME/.config/bcrc"
export TF_PLUGIN_CACHE_DIR="$HOME/.terraform.d/plugin-cache"

# shellcheck disable=SC2154
{
    export PATH="PATH/bin:$config_home/bin:$config_home/.local/bin:$config_home/.pyenv/bin:$config_home/.cargo/bin:$config_home/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
}

umask 0022
