#!/bin/sh

{
	erlang_version="28.0.4"
	export PATH="$HOME/.mix/escripts:$HOME"/src/misc/erlang/${erlang_version}/bin:"$PATH"
	#shellcheck source=/dev/null
	. "$HOME"/src/misc/erlang/${erlang_version}/activate
}
