#!/bin/bash
set -x

mod="Mod1"
alt="Mod4"
term="alacritty"

wobsock="$XDG_RUNTIME_DIR/wob.sock"
dmenu_args="-fn 'UW ttyp0:size=10' -l 10 -h 20 -nb '#130911' -nf '#d0d0d0' -sb '#3f2f40' -sf '#d0d0d0' -nhb '#130911' -nhf '#1dbfcf'"

rivertile -view-padding 0 -outer-padding 0 -main-ratio 0.50 &

riverctl border-color-focused "0xb33a4a"
riverctl border-color-unfocused "0x8b2a3a"
riverctl border-width 1

riverctl set-repeat 50 300

riverctl default-layout rivertile

riverctl input "pointer-1189-32769-BenQ_ZOWIE_BenQ_ZOWIE_Gaming_Mouse" pointer-accel 0.0
riverctl input "pointer-1133-45108-Logitech_MX_Master_3S" pointer-accel 0.0
riverctl input "pointer-1133-16500-Logitech_G305" pointer-accel 0.0

riverctl attach-mode top
riverctl focus-follows-cursor normal

riverctl map normal Super Return zoom

riverctl map normal $mod+Shift Return spawn "$term"
riverctl map normal $alt+Shift Return spawn "$term"

riverctl map normal $mod p spawn "dmenu_run $dmenu_args"
riverctl map normal $alt p spawn "dmenu_run $dmenu_args"

riverctl map normal Control+$alt l spawn "waylock"

riverctl map normal $alt b spawn "waybar_switch"

riverctl map normal $mod F1 spawn "firefox"
riverctl map normal $mod F3 spawn "pcmanfm-qt"
riverctl map normal $mod F4 spawn "picard"

riverctl map normal $mod+Shift p spawn "passmenu $dmenu_args"
riverctl map normal $mod+Shift m spawn "plsmenu $dmenu_args"
riverctl map normal $mod+Shift p spawn "passmenu $dmenu_args"
riverctl map normal $mod+Shift d spawn "clipmenu $dmenu_args"
riverctl map normal $alt+Shift m spawn "plsmenu $dmenu_args"
riverctl map normal $alt+Shift h spawn "huemenu $dmenu_args"
riverctl map normal $alt+Shift p spawn "passmenu $dmenu_args"
riverctl map normal $alt+Shift l spawn "langmenu $dmenu_args"
riverctl map normal $alt+Shift t spawn "tempmenu $dmenu_args"
riverctl map normal $alt+Shift d spawn "clipmenu $dmenu_args"
riverctl map normal $alt+Shift w spawn "define"

riverctl map normal $mod+Shift b spawn "btmenu con $dmenu_args"
riverctl map normal $alt+Shift b spawn "btmenu dis $dmenu_args"

riverctl map normal $mod+Shift s spawn "screenshot"
riverctl map normal $alt+Shift s spawn "screenshot"

riverctl map normal None XF86AudioMute spawn "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && (wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q MUTED && echo 0 > $wobsock) || wpctl get-volume @DEFAULT_AUDIO_SINK@ | sed 's/[^0-9]//g' > $wobsock"
riverctl map normal None XF86AudioLowerVolume spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && wpctl get-volume @DEFAULT_AUDIO_SINK@ | sed 's/[^0-9]//g' > $wobsock"
riverctl map normal None XF86AudioRaiseVolume spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && wpctl get-volume @DEFAULT_AUDIO_SINK@ | sed 's/[^0-9]//g' > $wobsock"

riverctl map normal None XF86MonBrightnessUp spawn "brightnessctl set +5% | sed -En 's/.*\(([0-9]+)%\).*/\1/p' > $wobsock"
riverctl map normal None XF86MonBrightnessDown spawn "brightnessctl set 5%- | sed -En 's/.*\(([0-9]+)%\).*/\1/p' > $wobsock"

riverctl map normal $mod+Shift c close
riverctl map normal $alt+Shift c close

riverctl map normal $mod j focus-view next
riverctl map normal $mod k focus-view previous

riverctl map normal $mod+Shift j swap next
riverctl map normal $mod+Shift k swap previous

riverctl map normal $mod h send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod l send-layout-cmd rivertile "main-ratio +0.05"

riverctl map normal $mod i send-layout-cmd rivertile "main-count +1"
riverctl map normal $mod d send-layout-cmd rivertile "main-count -1"

riverctl map normal $mod+Shift Space toggle-float

riverctl map normal $mod+Shift f toggle-fullscreen
riverctl map normal $alt+Shift f toggle-fullscreen

riverctl map normal $mod Space spawn "dunstctl close"
riverctl map normal $alt Space spawn "dunstctl history-pop"

for i in $(seq 1 9)
do
    tags=$((1 << (i - 1)))
    riverctl map normal $mod "$i" set-focused-tags "$tags"
    riverctl map normal $mod+Shift "$i" set-view-tags "$tags"
    riverctl map normal $mod+Control "$i" toggle-focused-tags "$tags"
    riverctl map normal $mod+Shift+Control "$i" toggle-view-tags "$tags"

    riverctl map normal $alt "$i" set-focused-tags "$tags"
    riverctl map normal $alt+Shift "$i" set-view-tags "$tags"
    riverctl map normal $alt+Control "$i" toggle-focused-tags "$tags"
    riverctl map normal $alt+Shift+Control "$i" toggle-view-tags "$tags"
done

riverctl map normal $mod 0 set-focused-tags $(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $(((1 << 32) - 1))
riverctl map normal $mod+Shift 0 set-view-tags $(((1 << 32) - 1))

riverctl map normal $alt 0 set-focused-tags $(((1 << 32) - 1))
riverctl map normal $alt 0 set-focused-tags $(((1 << 32) - 1))
riverctl map normal $alt+Shift 0 set-view-tags $(((1 << 32) - 1))

riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view
riverctl map-pointer normal $mod BTN_MIDDLE toggle-float

riverctl map normal $mod period focus-output next
riverctl map normal $mod comma focus-output previous

riverctl map normal $mod+Shift period send-to-output next
riverctl map normal $mod+Shift comma send-to-output previous

riverctl map normal $alt Tab focus-previous-tags
riverctl map normal $alt+Shift Tab send-to-previous-tags

riverctl map normal $mod Tab focus-previous-tags
riverctl map normal $mod+Shift Tab send-to-previous-tags

riverctl xcursor-theme default 16

pcmanfm-qt --daemon-mode &
swaybg -m fill -c "#15050f" -i "$HOME"/misc/random/wallpapers/13.jpg &

services_to_start=(
    "battery-notify"
    "cliphist"
    "dunst"
    "habitual"
    "kanshi"
    "listenbrainz-mpd"
    "plants-daemon"
    "ppctl-autoswitch"
    "psi-notify"
    "singlefile-sync"
    "swayidle"
    "wob"
    "xdg-desktop-portal"
    "xdg-desktop-portal-gtk"
    "xdg-desktop-portal-wlr"
)

for s in "${services_to_start[@]}"; do
    systemctl restart --user "$s"
done
