#!/bin/zsh

fzf_copy_from_cliphist() {
	{ cliphist list | fzf --no-sort | cliphist decode | wl-copy && zle reset-prompt || true } 2>/dev/null
}

erg() {
	$EDITOR \
		+'/\v'"${1/\//\\/}" \
		+':silent tabdo :1 | normal! n' \
		+':tabfirst' \
		-p $(rg "$@" | cut -d: -f1 | sort -u)
}

efd() {
	$EDITOR \
		+':tabfirst' \
		-p $(fd "$@")
}

# https://news.ycombinator.com/item?id=29155825
jog() {
	sqlite3 "$HOME/.histdb/zsh-history.db" "
        SELECT
            replace(commands.argv, '
', '
')
        FROM commands
        JOIN history ON history.command_id = commands.id
        JOIN places  ON history.place_id   = places.id
        WHERE history.exit_status = 0
          AND dir               = '${PWD}'
          AND places.host       = '${HOST}'
          AND commands.argv != 'jog'
          AND commands.argv != 'jog_run'
          AND commands.argv != 'j'
          AND commands.argv != 'jr'
          AND commands.argv NOT LIKE 'z %'
          AND commands.argv NOT LIKE 'cd %'
          AND commands.argv != '..'
        ORDER BY start_time DESC
    "
}

j() {
	local cmd
	cmd=$(jog | uniq | fzf --no-sort)
	[[ -n "$cmd" ]] && print -z "$cmd"
}

h() {
	if [ $# -eq 0 ]; then
		local cmd
		cmd=$(histdb --status 0 --sep "," |
			cut -d"," -f4 |
			grep -v "^(showing\|histdb" |
			uniq |
			tac |
			fzf --no-sort)
		[[ -n "$cmd" ]] && print -z "$cmd"
	else
		histdb "$@"
	fi
}

for b in $(seq 0 100); do
	alias b"$b"="sudo brightnessctl set $b%"

done
for t in $(seq 0 100); do
	alias s"$t"="seek $t"

done
for v in $(seq 0 100); do
	alias v"$v"="mpc volume $v"
done
