#!/bin/zsh

# https://github.com/zsh-users/zsh-autosuggestions
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#ff9580,bg=#000000,bold"

if [[ -f /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ]]; then
    . /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

# https://github.com/larkery/zsh-histdb
source $HOME/.config/zsh/plugins/zsh-histdb/sqlite-history.zsh
source $HOME/.config/zsh/plugins/zsh-histdb/histdb-interactive.zsh
autoload -Uz add-zsh-hook
bindkey '^r' _histdb-isearch

# https://github.com/hlissner/zsh-autopair
source $HOME/.config/zsh/plugins/zsh-autopair/autopair.zsh

# https://github.com/skywind3000/z.lua
source /usr/share/z.lua/z.lua.plugin.zsh

# ~/.config/shell/rc/magnolia
zle_fzf_change_file() {
    fgg && zle reset-prompt 2>/dev/null || true
}

zle_fzf_change_dir() {
    dg && zle reset-prompt 2>/dev/null || true
}

zle_fzf_freq_dir() {
    g && zle reset-prompt 2>/dev/null || true
}

zle -N zle_fzf_change_file
zle -N zle_fzf_change_dir
zle -N zle_fzf_freq_dir

bindkey '^H' 'zle_fzf_change_file'
bindkey '^K' 'zle_fzf_change_dir'
bindkey '^G' 'zle_fzf_freq_dir'

source $HOME/.config/zsh/plugins/twitch
