#!/bin/zsh

# https://github.com/larkery/zsh-histdb
source $HOME/.config/zsh/plugins/zsh-histdb/sqlite-history.zsh
source $HOME/.config/zsh/plugins/zsh-histdb/histdb-interactive.zsh
# https://github.com/hlissner/zsh-autopair
source $HOME/.config/zsh/plugins/zsh-autopair/autopair.zsh
# https://github.com/urbainvaes/fzf-marks
source $HOME/.config/zsh/plugins/fzf-marks/init.zsh
# https://github.com/zsh-users/zsh-syntax-highlighting
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

autoload -Uz add-zsh-hook
bindkey '^r' _histdb-isearch
